### ISSUE TITLE
프로필 편집중 비정상적으로 작동하는 비활성화 버튼 (프로필 변경 버튼)

### ISSUE THREAD

**Issue by NickYOOO** [jinoc-git/traduler-project#86]
# 이슈 개요
 - 프로필 변경버튼 활성화 조건 
   - 프로필 이미지가 변경 되었을 때
   - 닉네임 변경 후 중복확인을 통과 했을 때
   - 위에 두가지 조건이 만족했을 때
 
- 버그 조건
    - 사진제거 버튼을 누르면 무조건 활성화 
# 코드 위치
- src > components > main > profile > EditProfileModal.tsx

# 코드 
- 사진 제거 / 프로필 변경 코드
![스크린샷 2023-09-05 오후 11 16 30](https://github.com/jinoc-git/traduler-project/assets/108923582/60799ef5-9b17-4891-93de-6f6226c4b0e3)

- 사진 제거 함수
```tsx 
const removeAvartarBtnHandler = () => {
    setPreviewImg('');
    setIsRemoveAvatar(true);
  };
```
- 사진 제거 활성화 조건

```tsx 
const shouldBlockSubmitBtn: boolean
const shouldBlockSubmitBtn = isRemoveAvatar
  ? false
  : (!isAvatarChanged && !isNicknameChanged) ||
    (isNicknameChanged && isDuplicate);
   ```

**Comment by jinoc-git** [comment]
const isAvatarChanged = preview?.length !== 0;
const isNicknameChanged = nickname !== '';

const NicknameState = isNicknameChanged ? !isDuplicate : true;
const AvatarState = isAvatarChanged ? true : isRemoveAvatar;

const shouldBlockSubmitBtn = NicknameState && AvatarState;

// button
disabled={!shouldBlockSubmitBtn}

**Comment by NickYOOO** [comment]
- isAvatarChanged: 프로필 사진이 변경되었을 때 true.
- isNicknameChanged: 닉네임이 변경되었을 때 true.
- NicknameState: 닉네임이 변경되었고 중복이 아니면 true, 그렇지 않으면 항상 true.
- AvatarState: 프로필 사진이 변경되었으면 true, 그렇지 않으면 제거되었을 때 true.
- shouldBlockSubmitBtn: NicknameState와 AvatarState가 모두 true일 때 버튼을 활성화.

이렇게 이해가 되는데
const NicknameState = isNicknameChanged ? !isDuplicate : true;
- 이 코드에서 -> 닉네임이 변경되었고 중복이 아니면 true, 그렇지 않으면 항상 true. 로직으로 만들어 주셨는데 이유가 궁금합니다!

**Comment by jinoc-git** [comment]
닉네임이 변경이 있으면 중복 확인을 해야 하고, 없으면 이상 없으니 true입니다!

**Comment by NickYOOO** [comment]
#  버그 해결 진행중 
- 사진 제거 버튼을 눌렀을때  "프로필 변경" 버튼  무조건 활성화
- 닉네임 변경, 프로필 변경 버튼 활성화  이후 -> 사진 변경시 버튼 비활성화 
---
전반적인 로직 다시 변경 중 입니다.
